version: '3.8'
services:
  poste:
    container_name: poste
    image: analogic/poste.io:latest
    ports:
      - 25:25
      - 8080:8080
      - 443:443
      - 110:110
      - 143:143
      - 465:465
      - 587:587
      - 993:993
      - 995:995
    volumes:
      - ../data/poste:/data
    environment:
      - HTTPS=OFF
      - HTTP_PORT=8080
    restart: on-failure
