---
version: '3.8'
services:
  homer:
    container_name: homer
    image: b4bz/homer
    ports:
      - ${HOMER_EXPOSE_PORT}:8080
    volumes:
      - ../data/homer:/www/assets
    deploy:
      resources:
        limits:
          memory: 10M
        reservations:
          memory: 6M
    restart: on-failure
