version: '3.8'
services:
  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent
    ports:
        - 10050:10050
    environment:
        ZBX_HOSTNAME: ${ZBX_HOSTNAME}
        ZBX_SERVER_HOST: ${ZBX_SERVER_HOST}
    restart: on-failure