version: '3.8'
services:
  nginx-proxy-letsencrypt:
    container_name: nginx-proxy-letsencrypt
    image: ghcr.io/linuxserver/swag:latest
    ports:
      - 80:80
      - 443:443
    cap_add:
      - NET_ADMIN
    volumes:
      - ../data/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=yourdomain.url
      - SUBDOMAINS=www,
      - VALIDATION=http
      - DNSPLUGIN=cloudflare
      - PROPAGATION=
      - DUCKDNSTOKEN=
      - EMAIL=
      - ONLY_SUBDOMAINS=false
      - EXTRA_DOMAINS=
      - STAGING=false
      - MAXMINDDB_LICENSE_KEY=
    restart: on-failure
