version: '3.8'
services:
  letsencrypt:
    container_name: letsencrypt
    image: duch/letsencrypt-nginx-proxy-companion:stable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../data/letsencrypt/conf.d:/etc/nginx/conf.d
      - ../data/letsencrypt/html:/usr/share/nginx/html
      - vhostd:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs:rw
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx
      - NGINX_PROXY_CONTAINER=nginx
    restart: on-failure

volumes:
    certs:
    vhostd:
