version: '3.8'
services:
  confluence: 
    container_name: confluence
    image: atlassian/confluence-server:latest
    ports:
      - 80:80
    environment:
      - ATL_PROXY_NAME=confluence.internal
      - ATL_PROXY_PORT=80
      - ATL_TOMCAT_SCHEME=http
    restart: on-failure
