---
version: "3.6"
services:
  vscode:
    container_name: vscode
    image: linuxserver/code-server:latest
    ports:
      - 80:8443
    volumes:
      - ../data/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    restart: on-failure
