version: '3.8'
services:
  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    ports:
      - 9117:9117
    volumes:
      - ../data/jackett/config:/config
      - ../data/jackett/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - AUTO_UPDATE=true
      - RUN_OPTS=<run options here>
    restart: on-failure
