version: '3.8'
services:
  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server:latest
    ports:
      - ${MINECRAFT_EXPOSE_PORT:-25565}:25565
    volumes:
      - ../data:/data
    environment:
      EULA: "true"
      MOTD: ${MOTD}
      TYPE: ${TYPE}
      ONLINE_MODE: ${ONLINE_MODE}
      ENABLE_WHITELIST: ${WHITE_LIST}
    restart: on-failure
