version: '3.8'
services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    ports:
      - 7878:7878
    volumes:
      - ../data/radarr/config:/config
      - ../data/radarr/movies:/movies
      - ../data/radarr/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    restart: unless-stopped
