version: '3.8'
services:
  zabbix-java-gateway:
    container_name: zabbix-java-gateway
    image: zabbix/zabbix-java-gateway:latest
    restart: on-failure

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:latest
    depends_on:
        - zabbix-database
        - zabbix-java-gateway
    ports:
        - 10051:10051
    environment:
        DB_SERVER_HOST: zabbix-database
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        ZBX_JAVAGATEWAY: zabbix-java-gateway
        PHP_TZ: ${TIMEZONE}
    restart: on-failure

  zabbix-database:
    container_name: zabbix-database
    image: mysql:5.7
    ports:
        - 3306:3306
    volumes:
        - ../data/mysql:/var/lib/mysql
    environment:
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    restart: on-failure

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-nginx-mysql:latest
    depends_on:
        - zabbix-database
        - zabbix-server
    ports:
        - 80:8080
    environment:
        DB_SERVER_HOST: zabbix-database
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    restart: on-failure
